# pyproject.toml - metadata + dependency management (PEP 621)
[project]
name = "thesis-project"
version = "0.1.0"
description = "Data analysis project."
readme = "README.md"
authors = [
    { name = "Pedro Monteiro", email = "pedropessoamonteiro@gmail.com" }
]

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 88
indent-width = 4
target-version = "py39"

[tool.ruff.lint]
extend-select = ["E", "F", "N", "I", "SIM", "UP", "ALL"]
ignore = ["T201", "Q000", "ERA001", "D103", "W191", "PLR1702", "D100", "CPY001", "INP001"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
