# -*- coding: utf-8 -*-
"""feature_extraction_and_selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xzu4aPWZvLwQXsqPD3g-EEGQEXypfgOt
"""

import os
import re
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
from google.colab import files
import sklearn

drive.mount('/content/drive')
base_path = '/content/drive/MyDrive/CSI_DATA/CSI_DATA_positions_01_to_12/'

"""ESP configurations"""

esp_names = ['ESP1', 'ESP2', 'ESP3', 'ESP4']
num_esps = len(esp_names)

positions = {
    'z00_dia': [f'user00_positionz00_esp0{i}_dia.csv' for i in range(1, 5)],
    'z00_noite': [f'user00_positionz00_esp0{i}_noite.csv' for i in range(1, 5)],

    'a01': [f'user02_positiona01_esp0{i}.csv' for i in range(1, 5)],
    'a02': [f'user02_positiona02_esp0{i}.csv' for i in range(1, 5)],
    'a03': [f'user02_positiona03_esp0{i}.csv' for i in range(1, 5)],
    'a10': [f'user02_positiona10_esp0{i}.csv' for i in range(1, 5)],
    'a11': [f'user02_positiona11_esp0{i}.csv' for i in range(1, 5)],
    'a12': [f'user02_positiona12_esp0{i}.csv' for i in range(1, 5)],

    'b01': [f'user02_positionb01_esp0{i}.csv' for i in range(1, 5)],
    'b02': [f'user02_positionb02_esp0{i}.csv' for i in range(1, 5)],
    'b03': [f'user02_positionb03_esp0{i}.csv' for i in range(1, 5)],
    'b04': [f'user02_positionb04_esp0{i}.csv' for i in range(1, 5)],
    'b05': [f'user02_positionb05_esp0{i}.csv' for i in range(1, 5)],
    'b06': [f'user02_positionb06_esp0{i}.csv' for i in range(1, 5)],
    'b07': [f'user02_positionb07_esp0{i}.csv' for i in range(1, 5)],
    'b08': [f'user02_positionb08_esp0{i}.csv' for i in range(1, 5)],
    'b09': [f'user02_positionb09_esp0{i}.csv' for i in range(1, 5)],
    'b10': [f'user02_positionb10_esp0{i}.csv' for i in range(1, 5)],
    'b11': [f'user02_positionb11_esp0{i}.csv' for i in range(1, 5)],
    'b12': [f'user02_positionb12_esp0{i}.csv' for i in range(1, 5)],

    'c02': [f'user02_positionc02_esp0{i}.csv' for i in range(1, 5)],
    'c03': [f'user02_positionc03_esp0{i}.csv' for i in range(1, 5)],
    'c04': [f'user02_positionc04_esp0{i}.csv' for i in range(1, 5)],
    'c05': [f'user02_positionc05_esp0{i}.csv' for i in range(1, 5)],
    'c06': [f'user02_positionc06_esp0{i}.csv' for i in range(1, 5)],
    'c07': [f'user02_positionc07_esp0{i}.csv' for i in range(1, 5)],
    'c08': [f'user02_positionc08_esp0{i}.csv' for i in range(1, 5)],
    'c09': [f'user02_positionc09_esp0{i}.csv' for i in range(1, 5)],
    'c10': [f'user02_positionc10_esp0{i}.csv' for i in range(1, 5)],
    'c11': [f'user02_positionc11_esp0{i}.csv' for i in range(1, 5)],
    'c12': [f'user02_positionc12_esp0{i}.csv' for i in range(1, 5)],

    'd02': [f'user02_positiond02_esp0{i}.csv' for i in range(1, 5)],
    'd03': [f'user02_positiond03_esp0{i}.csv' for i in range(1, 5)],
    'd04': [f'user02_positiond04_esp0{i}.csv' for i in range(1, 5)],
    'd05': [f'user02_positiond05_esp0{i}.csv' for i in range(1, 5)],
    'd06': [f'user02_positiond06_esp0{i}.csv' for i in range(1, 5)],
    'd07': [f'user02_positiond07_esp0{i}.csv' for i in range(1, 5)],
    'd08': [f'user02_positiond08_esp0{i}.csv' for i in range(1, 5)],
    'd09': [f'user02_positiond09_esp0{i}.csv' for i in range(1, 5)],
    'd10': [f'user02_positiond10_esp0{i}.csv' for i in range(1, 5)],
    'd11': [f'user02_positiond11_esp0{i}.csv' for i in range(1, 5)],
    'd12': [f'user02_positiond12_esp0{i}.csv' for i in range(1, 5)],

    'e05': [f'user02_positione05_esp0{i}.csv' for i in range(1, 5)],
    'e06': [f'user02_positione06_esp0{i}.csv' for i in range(1, 5)],
    'e07': [f'user02_positione07_esp0{i}.csv' for i in range(1, 5)],
}

"""**Read and Process the CSI from the csv**"""

def read_rssi(file_name):
    df = pd.read_csv(base_path + file_name, header=None)
    return df.iloc[:, 4].astype(float).values

rssi_data = {}

def read_and_parse_csi(file_path, num_samples=120, selected_subcarriers=None):
    df = pd.read_csv(file_path, header=None)
    csi_raw = df.iloc[:num_samples, 26]
    valid_csi = []

    for entry in csi_raw:
        if pd.isna(entry) or '[' not in str(entry):
            continue
        try:
            nums = [int(n) for n in re.findall(r'-?\d+', str(entry))]
            if len(nums) == 128:
                valid_csi.append(nums)
        except ValueError:
            continue

    valid_csi = np.array(valid_csi)
    if valid_csi.shape[0] == 0:
        return np.empty((0, 0)), np.empty((0,))

    # 64 complex subcarriers
    complex_csi = valid_csi[:, ::2] + 1j * valid_csi[:, 1::2]

    # FFT shift puts DC in the center (index 32)
    fft_csi = np.fft.fftshift(complex_csi, axes=1)

    # Extract the 52 active subcarriers (IEEE 802.11n standard): [6:58]
    active = fft_csi[:, 6:58]

    # Remove subcarriers at positions 25, 26, 27 (center)
    active = np.delete(active, [25, 26, 27], axis=1)

    # Selecting specific subcarriers
    subcarrier_indices = [i for i in range(2, 48)]
    selected_subcarriers = np.array(subcarrier_indices)
    if selected_subcarriers is not None:
      active = active[:, selected_subcarriers]

    magnitudes = np.abs(active)
    return magnitudes

subcarrier_indices = [i for i in range(2, 48)]

csi_data = {}

for position, files in positions.items():
    for i, file_name in enumerate(files):
        path = base_path + file_name
        magnitudes= read_and_parse_csi(path, selected_subcarriers = subcarrier_indices)
        rssi_values = read_rssi(file_name)

        key = f"esp{i+1}_{position}"
        csi_data[key] = {"csi": magnitudes}

"""**Features**"""

def smooth(signal, n):
  # Make an array containing only zeros and with length = length_of_signal + 2*n
  extremes_zeros = np.zeros(len(signal) + 2*n)
  for i in range(len(signal)):
    if i < n:
      # mirror the start of signal
      extremes_zeros[i] = signal[n-i]
      # mirror the end of signal
      extremes_zeros[len(signal)+n+i] = signal[len(signal)-i-2]
    # fill the remaining with the signal itself
    extremes_zeros[i+n] = signal[i]

  # Build the arrayi
  smoothen_signal = np.zeros(len(signal))

  # Fill the array
  for i in range(n, len(extremes_zeros)-n):
    # Calculate the mean of the neighours - we have to look at the surrounding neighbours, thus we divide the total by 2 look back and further
    mean_neighbours = np.mean(extremes_zeros[i-n//2:i+n//2])
    smoothen_signal[i-n] = mean_neighbours

  return smoothen_signal

def aggregate_data_by_esp(csi_data, esp_prefix, normalization_mean, normalization_abs_max):
    X_total = []
    Y_total = []
    for key in csi_data:
        if key.startswith(esp_prefix):
            X_i = signal_processing_pipeline(csi_data[key]['csi'], normalization_mean, normalization_abs_max)
            X_total.append(X_i)

            # Extrai a posição do nome da chave (ex: 'esp1_a01' → 'a01')
            pos_str = key.split('_')[1]
            # Coluna → letra como número (a=1, b=2, ..., z=26), linha → número
            col = ord(pos_str[0]) - ord('a') + 1
            lin = int(pos_str[1:]) if pos_str[1:].isdigit() else 0
            Y_total.extend([[col, lin]] * len(X_i))

    return np.concatenate(X_total), np.array(Y_total)

"""**Normalization**"""

normalization_mean = {}
normalization_abs_max = {}

esp_ids = [1, 2, 3]

for esp_id in esp_ids:
    empty_csi_list = [
      csi_data[k]['csi']
      for k in csi_data
      if k.startswith(f'esp{esp_id}_') and k.endswith('_dia')
    ]

    if not empty_csi_list:
        print(f"no empty‐room data for ESP{esp_id}, skipping")
        continue
    all_empty = np.concatenate(empty_csi_list, axis=0)
    normalization_mean[esp_id]    = np.mean(all_empty,    axis=0)
    normalization_abs_max[esp_id] = np.max(np.abs(all_empty), axis=0)

def segments_signal(signal,window_size=10, no_overlap=2):
  segments = []
  t_segment = []

  for i in range(0, signal.shape[0], no_overlap):
    if i + window_size < signal.shape[0]:
      segment = signal[i:i+window_size]
      segments.append(segment) #cut segments
      t_segment.append(np.arange(i, i+window_size)) # cut time

  return segments, t_segment

def signal_processing_pipeline(csi_data, normalization_mean, normalization_abs_max):
  smoothened_data = []

  csi_data_normalized = csi_data - normalization_mean
  csi_data_normalized = csi_data_normalized / normalization_abs_max

  # Iterate over the subsampled data and smoothen the signals
  for signal in csi_data_normalized.T: #for each columns
    smoothened_signal = smooth(signal, 20) # Subsample by a factor of 5
    smoothened_data.append(smoothened_signal)

  segments, t_segments = segments_signal(csi_data_normalized)
  segments = np.array(segments)
  features = [np.mean(segments, axis=1), np.std(segments, axis=1)]
  features = np.array(features)
  X = np.transpose(features, (1,0,2))
  X = X.reshape(X.shape[0], -1)

  return X

"""**Machine learning**"""

def generate_X_Y_for_esp(esp_id, normalization_mean, normalization_abs_max):
    X_total = []
    Y_total = []
    for key in csi_data:
        if key.startswith(f'esp{esp_id}_'):
            csi = csi_data[key]['csi']
            X = signal_processing_pipeline(csi, normalization_mean, normalization_abs_max)
            X_total.append(X)

            # Extração da posição (ex: a01 → coluna=a, linha=01)
            pos = key.split("_")[1]
            col = ord(pos[0]) - ord('a') + 1
            row = int(pos[1:]) if pos[1:].isdigit() else 0
            Y_total.extend([[col, row]] * len(X))

    return np.concatenate(X_total), np.array(Y_total)

XY = {
    esp: generate_X_Y_for_esp(
        esp,
        normalization_mean[esp],
        normalization_abs_max[esp]
    )
    for esp in esp_ids
}

X_1, Y_1 = XY[1]
X_2, Y_2 = XY[2]
X_3, Y_3 = XY[3]
#X_4, Y_4 = XY[4]

"""**2 Models - 1 for Columns & 1 for Lines**"""

X = np.concatenate([X_1, X_2, X_3])

Y = np.concatenate([Y_1, Y_2, Y_3])
Y = np.array(Y)

print("Unique Columns:", np.unique(Y[:, 0]))
print("Unique Lines:", np.unique(Y[:, 1]))

import sklearn as skl

X_train, X_test, y_train, y_test = skl.model_selection.train_test_split(X, Y, test_size=0.3, random_state=200)


column_model = sklearn.ensemble.RandomForestClassifier(random_state=200)
column_model.fit(X_train, y_train[:,0])

line_model = sklearn.ensemble.RandomForestClassifier(random_state=200)
line_model.fit(X_train, y_train[:,1])

# Predictions
pred_col = column_model.predict(X_test)
pred_line = line_model.predict(X_test)

# Compute raw confusion matrices
cm_col = skl.metrics.confusion_matrix(y_test[:, 0], pred_col)
cm_line = skl.metrics.confusion_matrix(y_test[:, 1], pred_line)

def normalize_confusion_matrix(cm):
    cm = cm.astype(float)
    row_sums = np.sum(cm, axis=1, keepdims=True)
    return cm / row_sums

# Normalize confusion matrices
confusion_matrix_column = normalize_confusion_matrix(cm_col)
confusion_matrix_line = normalize_confusion_matrix(cm_line)

confusion_matrix_column = skl.metrics.confusion_matrix(y_test[:,0], pred_col, normalize='true')
confusion_matrix_line = skl.metrics.confusion_matrix(y_test[:,1], pred_line, normalize='true')


balanced_acc_column = skl.metrics.balanced_accuracy_score(y_test[:, 0], pred_col)
balanced_acc_line = skl.metrics.balanced_accuracy_score(y_test[:, 1], pred_line)

print("Balanced Accuracy (Column):", balanced_acc_column)
print("Balanced Accuracy (Line):", balanced_acc_line)

'''
plt.imshow(confusion_matrix_column, cmap='Spectral', vmin=0, vmax=1)
plt.colorbar()
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title("Confusion Matrix - Column")

import google.colab.files as colab_files


plt.savefig('confusion_matrix_column.png', format='png')
colab_files.download('confusion_matrix_column.png')
plt.show()
'''

'''
plt.imshow(confusion_matrix_line, cmap='Spectral', vmin=0, vmax=1)
plt.colorbar()

plt.xlabel('Predicted')
plt.ylabel('True')
plt.title("Confusion Matrix - Line")

plt.savefig('confusion_matrix_line.png', format='png')
colab_files.download('confusion_matrix_line.png')
plt.show()
'''

"""# **1º MODELO:  “Baseline” Random Forest on Raw Features**

**1 Model - Columns & Lines**
"""

X = np.concatenate([X_1, X_2, X_3])

Y_raw = np.concatenate([Y_1, Y_2, Y_3])
col_lin_to_label = {}
label_to_col_lin = {}
next_label = 0

labels = []
for col, lin in Y_raw:
    key = (col, lin)
    if key not in col_lin_to_label:
        col_lin_to_label[key] = next_label
        label_to_col_lin[next_label] = key
        next_label += 1
    labels.append(col_lin_to_label[key])

Y = np.array(labels)

X_train, X_test, y_train, y_test = skl.model_selection.train_test_split(X, Y, test_size=0.3, random_state=200)

position_model = sklearn.ensemble.RandomForestClassifier(random_state=200)
position_model.fit(X_train, y_train)

# Predict
y_pred = position_model.predict(X_test)

# Raw confusion matrix
cm_pos = skl.metrics.confusion_matrix(y_test, y_pred)

# Manual normalization (row-wise)
confusion_matrix_normalized = []
for row_values in cm_pos:
    confusion_matrix_normalized.append(row_values / np.sum(row_values))
cm_pos_norm = np.array(confusion_matrix_normalized)

accuracy = skl.metrics.accuracy_score(y_test, y_pred)
print("Accuracy (Combined Position):", accuracy)

'''
labels_names = [f"{chr(col + ord('a') - 1)}{str(lin).zfill(2)}" for (col, lin) in [label_to_col_lin[i] for i in range(len(label_to_col_lin))]]

fig, ax = plt.subplots(figsize=(12, 10))
sns.heatmap(
    cm_pos_norm, cmap='Spectral', vmin=0, vmax=1, xticklabels=positions, yticklabels=positions,)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.title('Normalized Confusion Matrix - Combined Position')


plt.savefig('confusion_matrix_combined.png', format='png')
colab_files.download('confusion_matrix_combined.png')
plt.show()
'''

confusion_matrix_normalized[14]

recall = np.diag(cm_pos) / cm_pos.sum(axis=1)

filtered = {lbl:(c,r)
            for lbl,(c,r) in label_to_col_lin.items()
            if r>=1 and c<=5}

max_col = 5
max_row = max(r for c,r in filtered.values())

grid = np.full((max_row, max_col), np.nan)

for label, (c, r) in filtered.items():
    grid[r-1, c-1] = recall[label]

import matplotlib as mpl
from matplotlib.ticker import PercentFormatter


fig, ax = plt.subplots(figsize=(4, 8))
ax.set_facecolor('#f7f7f7')

norm = mpl.colors.Normalize(vmin=0.50, vmax=1.00)
im = ax.imshow(grid, origin='lower', cmap='RdYlGn', interpolation='nearest', aspect='equal', norm=norm)

cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.04, format=PercentFormatter(xmax=1.0))
cb.set_label('Accuracy (%)', fontsize=10, weight='medium')
cb.set_ticks([0.50, 0.60, 0.70, 0.80, 0.90, 1.00])
cb.outline.set_linewidth(0.8)
cb.ax.tick_params(width=0.8)

ax.set_xticks(np.arange(-0.5, max_col, 1), minor=True)
ax.set_yticks(np.arange(-0.5, max_row, 1), minor=True)
ax.grid(which='minor', color='grey', alpha=0.3, linewidth=1)
ax.tick_params(which='minor', length=0)

# Add numeric values
for r in range(max_row):
    for c in range(max_col):
        v = grid[r, c]
        if not np.isnan(v):
            ax.text(c, r, f"{v*100:.1f}%", ha='center', va='center', fontsize=8, fontweight='semibold',
                    bbox=dict(facecolor='white', alpha=0.4, boxstyle='round,pad=0.1', linewidth=0), color='black')

# Add custom text annotations for ESPs and AP
label_font = dict(ha='center', va='center', fontsize=8.5, fontweight='bold', color='black')

ax.text(ord('C'.lower()) - ord('a'), 0, 'ESP1', **label_font)  # C01 → row 0, col 2
ax.text(ord('E'.lower()) - ord('a'), 9, 'ESP2', **label_font)  # E10 → row 9, col 4
ax.text(ord('E'.lower()) - ord('a'), 3, 'ESP3', **label_font)  # E04 → row 3, col 4
#ax.text(ord('A'.lower()) - ord('a'), 8, 'ESP4', **label_font)  # A09 → row 8, col 0
ax.text(ord('A'.lower()) - ord('a'), 7, 'AP',    **label_font)  # A08 → row 7, col 0

# Axis ticks and labels
ax.set_xticks(np.arange(max_col))
ax.set_xticklabels([chr(ord('a') + j).upper() for j in range(max_col)], fontsize=12)
ax.set_yticks(np.arange(max_row))
ax.set_yticklabels([f"{i+1:02d}" for i in range(max_row)], fontsize=10)

ax.set_xlabel('Column', fontsize=14)
ax.set_ylabel('Row', fontsize=14)
#ax.set_title('Probability of correct prediction by room position (using 4 ESPs)', fontsize=12, pad=10)

ax.invert_xaxis()
fig.savefig('heatmap_remove_ESP4_.png', format='png', dpi=300, bbox_inches='tight', pad_inches=0.2)
from google.colab import files
#files.download('heatmap_remove_ESP4_.png')
plt.show()

import time, math
from collections import defaultdict
import numpy as np

def p95(a):
    return float(np.percentile(a, 95)) if len(a) else float('nan')

timings = defaultdict(list)

def timed_read_and_parse(path):
    t0 = time.perf_counter()
    mags = read_and_parse_csi(path, selected_subcarriers=subcarrier_indices)
    timings['parse_ms'].append((time.perf_counter()-t0)*1e3)
    return mags

def signal_processing_pipeline_timed(csi_data, normalization_mean, normalization_abs_max, use_smoothing=True):
    t0 = time.perf_counter()
    Xn = (csi_data - normalization_mean) / normalization_abs_max
    timings['pre_ms'].append((time.perf_counter()-t0)*1e3)

    if use_smoothing:
        t1 = time.perf_counter()
        Xs = moving_average(Xn, n=20)
        timings['smooth_ms'].append((time.perf_counter()-t1)*1e3)
    else:
        Xs = Xn

    t2 = time.perf_counter()
    segments, _ = segments_signal(Xs, window_size=10, no_overlap=2)
    segments = np.array(segments)
    # Example features: mean & std
    feats = np.stack([segments.mean(axis=1), segments.std(axis=1)], axis=1)
    X = feats.reshape(feats.shape[0], -1)
    timings['feat_ms'].append((time.perf_counter()-t2)*1e3)
    return X

def batch_predict_timed(model, X):
    t0 = time.perf_counter()
    y = model.predict(X)
    timings['infer_ms'].append((time.perf_counter()-t0)*1e3)
    return y

# --- Warm-up (important for fair timing) ---
_ = position_model.predict(X[:64])

# --- Measure on your test split ---
# Here we simulate real-time by replaying file groups through the pipeline.
# If you want per-file timings, loop over files instead.
N = min(50, len(X_test))  # cap for speed
_ = position_model.predict(X_test[:5])  # extra warmup

t_total = []
for i in range(N):
    t0 = time.perf_counter()
    # We already have X_test ready-made; to include all stages, rebuild features from raw csi for a subset.
    # Example: pick any key with enough samples and run end-to-end once per iteration.
    # If you have a mapping from X to file paths, use it here. Otherwise, just time pre+feat+infer:
    Xi = X_test[i:i+1]
    _ = batch_predict_timed(position_model, Xi)
    t_total.append((time.perf_counter()-t0)*1e3)

# --- Summary table ---
def summarize(name):
    arr = np.array(timings[name])
    return dict(mean_ms=float(arr.mean()), std_ms=float(arr.std()), p95_ms=p95(arr), n=len(arr))

summary = {k: summarize(k) for k in timings.keys()}
summary['total_loop_ms'] = dict(mean_ms=float(np.mean(t_total)),
                                std_ms=float(np.std(t_total)),
                                p95_ms=p95(t_total),
                                n=len(t_total))

summary

"""**Worst Positions**"""

'''
recall_per_label = np.diag(cm_pos_norm)
recall_by_pos = {
    label_to_col_lin[i]: recall_per_label[i]
    for i in range(len(recall_per_label))
}
sorted_positions = sorted(recall_by_pos.items(), key=lambda kv: kv[1])
filtered_positions = [
    (pos, r) for pos, r in sorted_positions
    if pos[1] > 0
    and pos[0] <= 5
]

worst_positions = [pos for pos,_ in filtered_positions[:3]]
best_positions  = [pos for pos,_ in filtered_positions[-3:]]

def pos_to_name(pos):
    col, row = int(pos[0]), int(pos[1])
    return f"{chr(col + ord('A') - 1)}{row:02d}"

worst_names = [pos_to_name(p) for p in worst_positions]
best_names  = [pos_to_name(p) for p in best_positions]

print("Worst positions:", worst_names)
print("Best  positions:", best_names)
'''

'''
def plot_confusion_row_ax(pos, cm_norm, label_map, ax, max_cols=5, cmap='Spectral'):
    lbl = next(i for i,(c,r) in label_map.items() if (c,r)==pos)
    row = cm_norm[lbl]
    max_row = max(r for c,r in label_map.values() if c<=max_cols)
    grid = np.full((max_row, max_cols), np.nan)
    for i, p in enumerate(row):
        c, r = label_map[i]
        if 1<=c<=max_cols and 1<=r<=max_row:
            grid[r-1,c-1] = p
    ax.set_facecolor('#f7f7f7')
    im = ax.imshow(grid, origin='lower', cmap = cmap, vmin=0, vmax=0.6, interpolation='nearest', aspect='equal')

    for rr in range(grid.shape[0]):
        for cc in range(grid.shape[1]):
            v = grid[rr,cc]
            if not np.isnan(v) and v > 0:
                ax.text(cc, rr, f"{v*100:.1f}%", ha='center', va='center', fontsize=8, weight='semibold',
                        bbox=dict(facecolor='white', alpha=0.5, pad=0.1, linewidth=0))

    ax.set_xticks(np.arange(max_cols))
    ax.set_xticklabels([chr(65+j) for j in range(max_cols)], fontsize=10)
    ax.set_yticks(np.arange(grid.shape[0]))
    ax.set_yticklabels([f"{i+1:02d}" for i in range(grid.shape[0])], fontsize=10)
    ax.set_xlabel('Column')
    ax.set_ylabel('Row')
    ax.set_title(f"{chr(pos[0]+64)}{pos[1]:02d}", pad=6)
    ax.invert_xaxis()
    return im
'''

'''
fig_w, axs_w = plt.subplots( 1, len(worst_positions), figsize=(len(worst_positions)*4, 8), constrained_layout=True)

for ax, pos in zip(axs_w, worst_positions):
    im = plot_confusion_row_ax( pos, cm_pos_norm, label_to_col_lin, ax, max_cols=5, cmap = 'Reds')

cbar = fig_w.colorbar(im, ax=axs_w, fraction=0.046, pad=0.04)
cbar.set_label('P(pred | true)', weight='medium')
fig_w.suptitle("Three Worst-Performing Positions", fontsize=16, weight='regular', y=1.02)


fig_w.savefig('worst_positions.png', format='png')
colab_files.download('worst_positions.png')
plt.show()
'''

'''
fig_b, axs_b = plt.subplots(
    1, len(best_positions),
    figsize=(len(best_positions)*4, 8),
    constrained_layout=True
)
for ax, pos in zip(axs_b, best_positions):
    im = plot_confusion_row_ax( pos, cm_pos_norm, label_to_col_lin, ax, max_cols=5, cmap='Greens')
cbar = fig_b.colorbar(im, ax=axs_b, fraction=0.046, pad=0.04)
cbar.set_label('P(pred | true)', weight='medium')
fig_b.suptitle("Three Best-Performing Positions", fontsize=16, weight='regular', y=1.02)


fig_b.savefig('best_positions.png', format='png')
colab_files.download('best_positions.png')
plt.show()
'''

"""# **2º MODELO: Grid-Search over Random Forest Hyper-parameters - 82,80%**"""

'''X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split( X, Y, test_size=0.3, random_state=200)

n_estimators        = [100, 200]
criterion           = ["gini", "entropy"]
max_depth           = [None, 10, 20]
min_samples_splits  = [2, 5]
min_samples_leafs   = [1, 2]

balanced_accuracy_dict = {}
for n in n_estimators:
    for c in criterion:
        for m in max_depth:
            for s in min_samples_splits:
                for l in min_samples_leafs:
                    clf = sklearn.ensemble.RandomForestClassifier(
                        n_estimators=n,
                        criterion=c,
                        max_depth=m,
                        min_samples_split=s,
                        min_samples_leaf=l,
                        random_state=200
                    )
                    clf.fit(X_train, y_train)
                    y_pred = clf.predict(X_test)
                    bal_acc = skl.metrics.balanced_accuracy_score(y_test, y_pred)
                    balanced_accuracy_dict[(n, c, m, s, l)] = bal_acc

sorted_results = sorted(balanced_accuracy_dict.items(), key=lambda x: x[1], reverse=True)

print("\nTop 10 Configurations by Accuracy:")
for i, ((n, c, m, s, l), score) in enumerate(sorted_results[:10], 1):
    print(f"{i}. Params: n_estimators={n}, criterion={c}, max_depth={m}, "
          f"min_samples_split={s}, min_samples_leaf={l} -> Accuracy: {score:.4f}")'''

"""# **3º MODELO: CNN-Autoencoder + Random Forest on Learned Embeddings - Test Col Acc: 0.7370, Test Row Acc: 0.5322**"""

'''import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Reshape, Conv1D, Dense, Activation, Flatten, Input, Conv2D, MaxPooling2D, Flatten, Conv2D, MaxPooling2D
from PIL import Image
import numpy as np
import cv2
import matplotlib.pyplot as plt

# 1) find unique labels
unique_cols = np.unique(Y_raw[:,0])
unique_rows = np.unique(Y_raw[:,1])

col_to_idx = {c:i for i,c in enumerate(unique_cols)}
row_to_idx = {r:i for i,r in enumerate(unique_rows)}

y_col_idx = np.array([col_to_idx[c] for c in Y_raw[:,0]])
y_row_idx = np.array([row_to_idx[r] for r in Y_raw[:,1]])

num_cols = len(unique_cols)
num_rows = len(unique_rows)


# Normalizar
scaler = sklearn.preprocessing.MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_padded = np.pad(X_scaled, ((0, 0), (0, 96 - X_scaled.shape[1])), mode='constant')
X_cnn = X_padded.reshape((X_padded.shape[0], 96, 1))


y_col = tf.keras.utils.to_categorical(y_col_idx, num_cols)
y_row = tf.keras.utils.to_categorical(y_row_idx, num_rows)

X_tr, X_temp, ycol_tr, ycol_temp, yrow_tr, yrow_temp =skl.model_selection.train_test_split(X_cnn, y_col, y_row, test_size=0.4, random_state=200)
X_val, X_te, ycol_val, ycol_te, yrow_val, yrow_te = skl.model_selection.train_test_split(X_temp, ycol_temp, yrow_temp, test_size=0.5, random_state=200)

input_dim = 96
input_layer = Input(shape=(input_dim, 1))

# Encoder
x = Conv1D(64, 3, activation='relu', padding='same')(input_layer)
x = tf.keras.layers.MaxPooling1D(2, padding='same')(x)
x = Conv1D(32, 3, activation='relu', padding='same')(x)
x = tf.keras.layers.MaxPooling1D(2, padding='same')(x)
x = Conv1D(16, 3, activation='relu', padding='same')(x)
x = tf.keras.layers.MaxPooling1D(2, padding='same')(x)

# Bottleneck + dense layers
x = Flatten()(x)
x = Dense(2048, activation='relu')(x)
shared = Dense(512, activation='relu')(x)

# Heads
col_out = Dense(num_cols, activation='softmax', name="classifier_col")(shared)
row_out = Dense(num_rows, activation='softmax', name="classifier_row")(shared)

model = Model(inputs=input_layer, outputs=[col_out, row_out])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss={"classifier_col":"categorical_crossentropy",
          "classifier_row":"categorical_crossentropy"},
    metrics={"classifier_col":"accuracy",
             "classifier_row":"accuracy"}
)

model.summary()


# 5) fit with validation_data
history = model.fit(
    X_tr,
    {"classifier_col": ycol_tr, "classifier_row": yrow_tr},
    epochs=50,
    batch_size=64,
    validation_data=(X_val, {"classifier_col": ycol_val, "classifier_row": yrow_val})
)'''

'''# 7) evaluate on test set
evals = model.evaluate(
    X_te,
    {"classifier_col": ycol_te, "classifier_row": yrow_te},
    verbose=1
)
print(f"\nTest Col Acc: {evals[3]:.4f}, Test Row Acc: {evals[4]:.4f}")

'''

'''
# Bottleneck
x = Flatten()(x)

# Classifier
encoded = Dense(2048, activation='linear')(x)
encoded = Dense(512, activation='linear')(encoded)
output_col = Dense(5, activation='softmax', name="classifier_col")(encoded)
output_row = Dense(12, activation='softmax', name="classifier_row")(encoded)

# Build the model
col_model = tf.keras.Model(inputs=input_layer, outputs=output_col)
optimizer= tf_keras.optimizers.Adam(learning_rate=0.0001)
col_model.compile(optimizer=optimizer, loss='categorical_crossentropy')
col_model.summary()

row_model = tf.keras.Model(inputs=input_layer, outputs=output_row)
optimizer= tf_keras.optimizers.Adam(learning_rate=0.0001)
row_model.compile(optimizer=optimizer, loss='categorical_crossentropy')
row_model.summary()


''''''
# Decoder
x = Dense((input_dim // 8) * 16, activation='relu')(encoded)
x = Reshape((input_dim // 8, 16))(x)  # Reconstrói para 1D
x = tf.keras.layers.UpSampling1D(2)(x)
x = Conv1D(32, 3, activation='relu', padding='same')(x)
x = tf.keras.layers.UpSampling1D(2)(x)
x = Conv1D(64, 3, activation='relu', padding='same')(x)
x = tf.keras.layers.UpSampling1D(2)(x)
decoded = Conv1D(1, 3, activation='sigmoid', padding='same')(x)

# Autoencoder
autoencoder = tf.keras.Model(inputs=input_layer, outputs=decoded)
autoencoder.compile(optimizer='adam', loss='mse')
autoencoder.summary()
''''''

col_model.fit(X_train_auto, np.eye(5)[y_col], epochs=50, batch_size=64)
#one hot vector
row_model.fit(X_train_auto, np.eye(12)[y_row], epochs=50, batch_size=64)
#gravar os modelos depois de treinados
#ver o loss do treino
#meter validação


X_train_encoded = encoder.predict(X_train_auto)
X_test_encoded = encoder.predict(X_test_auto)
encoder = Model(autoencoder.input, autoencoder.get_layer('bottleneck').output)

X_encoded = encoder.predict(X_cnn)

col_lin_to_label = {}
label_to_col_lin = {}
next_label = 0
Y_combined = []
for col, row in Y_raw:
    key = (col, row)
    if key not in col_lin_to_label:
        col_lin_to_label[key] = next_label
        label_to_col_lin[next_label] = key
        next_label += 1
    Y_combined.append(col_lin_to_label[key])
Y_combined = np.array(Y_combined)

X_tr, X_te, y_raw, y_te = sklearn.model_selection.train_test_split(
    X_encoded, Y_combined,
    test_size=0.3, random_state=200
)

clf =  sklearn.ensemble.RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

clf.fit(X_tr, y_raw)

y_pred = clf.predict(X_te)
acc     = sklearn.metrics.accuracy_score(y_te, y_pred)
print(f"Accuracy (combined):          {acc:.4f}")
'''

